# アプリ全体の設定
spring.application.name=my-app
server.port=${PORT:8080}

# DB接続設定
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# myBatisの設定
mybatis.configuration.map-underscore-to-camel-case = true

logging.level.com.example.my_app.domain.repository=DEBUG